version: "3.9"

services:

  api:
    build: ./
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      - GOOGLE_CLIENT_ID=997903370004-9eikvl4h0hsov8oaopucuon9mj80t1hf.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REDIRECT_URI=http://localhost:8000/auth/google
      - authjwt_secret_key=0lCU8ghbHhKCKFBw3UnVlQUyHSXOIKfZN2pdlUoDRkpY6TM6kleGveuIetQo9zS1
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=alpha
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database

  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=alpha
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  api:
